steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/question-salad/google-cloud-test', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/question-salad/google-cloud-test']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    [
      'run', 'deploy', 'google-cloud-test',
      '--image', 'gcr.io/question-salad/google-cloud-test',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
